sonar.projectKey=onlineboutique
sonar.projectName=Online Boutique Microservices
sonar.language=multi
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/genproto/**,**/proto/**,**/gradle/wrapper/**,**/node_modules/**,**/__pycache__/**,**/*.pb2.py,**/*.pb2_grpc.py

# Go
sonar.go.exclusions=**/genproto/**

# Python
sonar.python.exclusions=**/genproto/**,**/demo_pb2*

# Java
sonar.java.binaries=src/adservice/build

# JavaScript/TypeScript
sonar.javascript.exclusions=**/node_modules/**,**/proto/**
